version: '3.8'

services:
  pg:
    image: postgres:latest
    container_name: postgres
    restart: always
    environment:
      POSTGRES_DB: dtb
      POSTGRES_USER: usr
      POSTGRES_PASSWORD: psw
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-net
    ports:
      - "5444:5432"

  python:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: python_web
    restart: always
    environment:
      DATABASE_URL: postgresql://usr:psw@pg:5432/dtb
    depends_on:
      - pg
    networks:
      - app-net

  nginx:
    image: nginx:latest
    container_name: nginx
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - python
    networks:
      - app-net

volumes:
  postgres_data:

networks:
  app-net:
    driver: bridge